name: corpus
version: 0.0.1

description: >-
  Dart/Flutter code-mining corpus experiments

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  args: ^1.6.0
  cli_util: ^0.1.3+2
  meta: ^1.0.0
  path: ^1.2.0

dev_dependencies:
  pedantic: ^1.9.0
